<?php

return [
    'basic' => [
        'name'              => 'Basic',
        'name_ar'           => 'الأساسية',
        'tagline'           => 'Perfect for getting started',
        'tagline_ar'        => 'مثالي للبداية',
        'monthly_price'     => 29,
        'yearly_price'      => 278,
        'yearly_discount'   => 20,
        'max_products'      => 50,
        'has_3d'             => false,
        'monthly_3d_credits' => 0,
        'has_analytics'     => false,
        'has_featured'      => false,
        'support_level'     => 'Email Support',
        'support_level_ar'  => 'دعم عبر البريد',
        'commission_rate'   => 10,
        'color'             => '#888888',
        'features' => [
            'Up to 50 products',
            'Branded store page',
            'Basic analytics',
            'Email support',
            'Voxura checkout',
            'Order management',
        ],
        'features_ar' => [
            'حتى 50 منتج',
            'صفحة متجر مخصصة',
            'تحليلات أساسية',
            'دعم عبر البريد',
            'نظام دفع Voxura',
            'إدارة الطلبات',
        ],
    ],
    'pro' => [
        'name'              => 'Pro',
        'name_ar'           => 'المتقدمة',
        'tagline'           => 'For growing stores',
        'tagline_ar'        => 'للمتاجر النامية',
        'monthly_price'     => 79,
        'yearly_price'      => 758,
        'yearly_discount'   => 20,
        'max_products'      => 200,
        'has_3d'             => true,
        'monthly_3d_credits' => 10,
        'has_analytics'     => true,
        'has_featured'      => false,
        'support_level'     => 'Priority Support',
        'support_level_ar'  => 'دعم ذو أولوية',
        'commission_rate'   => 8,
        'color'             => '#E8621A',
        'popular'           => true,
        'features' => [
            'Up to 200 products',
            'Everything in Basic',
            '3D product visualization',
            'Virtual try-on',
            'Advanced analytics',
            'Priority support',
            '8% commission rate',
            'Featured store eligibility',
        ],
        'features_ar' => [
            'حتى 200 منتج',
            'كل مزايا الأساسية',
            'عرض المنتجات ثلاثي الأبعاد',
            'التجربة الافتراضية',
            'تحليلات متقدمة',
            'دعم ذو أولوية',
            'عمولة 8% فقط',
            'أهلية للمتجر المميز',
        ],
    ],
    'premium' => [
        'name'              => 'Premium',
        'name_ar'           => 'الاحترافية',
        'tagline'           => 'For established brands',
        'tagline_ar'        => 'للعلامات التجارية الراسخة',
        'monthly_price'     => 149,
        'yearly_price'      => 1430,
        'yearly_discount'   => 20,
        'max_products'      => -1,
        'has_3d'             => true,
        'monthly_3d_credits' => 50,
        'has_analytics'     => true,
        'has_featured'      => true,
        'support_level'     => 'Dedicated Support',
        'support_level_ar'  => 'مدير حساب مخصص',
        'commission_rate'   => 5,
        'color'             => '#7F77DD',
        'features' => [
            'Unlimited products',
            'Everything in Pro',
            'Dedicated account manager',
            'Featured store placement',
            'Custom accent colors',
            'API access',
            '5% commission rate',
            'Early access to new features',
        ],
        'features_ar' => [
            'منتجات غير محدودة',
            'كل مزايا المتقدمة',
            'مدير حساب مخصص',
            'موضع المتجر المميز',
            'ألوان مخصصة',
            'وصول API',
            'عمولة 5% فقط',
            'وصول مبكر للمزايا الجديدة',
        ],
    ],
    'custom' => [
        'name'          => 'Custom',
        'name_ar'       => 'مخصصة',
        'tagline'       => 'Tailored for your business',
        'tagline_ar'    => 'مصممة لاحتياجاتك',
        'monthly_price' => null,
        'yearly_price'  => null,
        'color'         => '#1D9E75',
        'has_3d'             => true,
        'monthly_3d_credits' => 0,
        'contact_only'  => true,
        'commission_rate' => null,
        'features' => [
            'Everything in Premium',
            'Custom pricing',
            'Custom commission rate',
            'White-label options',
            'Dedicated infrastructure',
            'SLA guarantee',
            'Custom integrations',
        ],
        'features_ar' => [
            'كل مزايا الاحترافية',
            'تسعير مخصص',
            'عمولة مخصصة',
            'خيارات العلامة البيضاء',
            'بنية تحتية مخصصة',
            'ضمان مستوى الخدمة',
            'تكاملات مخصصة',
        ],
    ],
];
